version = 0.1

[default.deploy.parameters]
stack_name = "slack-rag-prod-v2"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
no_fail_on_empty_changeset = true
template_file = "infra/sam/template.yaml"

parameter_overrides = [
  "ArtifactsBucket=your-s3-bucket-name",
  "RagApiUrl=https://your-api-url/Prod/chat",
  "SlackBotTokenArn={{your-slackbot-secret-id}}",
  "SlackSigningSecretArn={{your-slacksigning-secret-id}}",
  "Environment=prod"
]


